# config.py

# 摄像头设置
CAM_INDEX=0
# CAM_INDEX='/dev/video0'
FRAME_WIDTH = 640
FRAME_HEIGHT = 480

# ROI 区域设置（按比例）
ROI_LEFT_RATIO = 0.3
ROI_RIGHT_RATIO = 0.7
ROI_TOP_RATIO = 0.3
ROI_BOTTOM_RATIO = 0.8

# 斜率判断
SLOPE_VERTICAL_THRESHOLD = 1000
MIN_LINE_WIDTH_RATIO = 0.1

# 检测逻辑参数
LINE_DETECTION_COUNT = 4
DETECTION_TIME_INTERVAL = 5  
MAX_REVERSE = 2   #倒车任务总次数
REVERSING_TIMEOUT = 20   #倒车时间
LEAVE_GARAGE_TIMEOUT=20   #出库时间


# 显示
STACK_SCALE = 0.5

# 串口设置
# SERIAL_PORT = '/dev/ttyAMA0'
# BAUD_RATE = 115200

